dist: bionic
os: linux
language: generic

cache:
  directories:
  - $HOME/.local/share/NuGet/
  - $HOME/.nuget

addons:
  postgresql: "10"
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    - sourceline: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'

services:
  - postgresql
  - mysql

before_install:
- sudo apt-get install -y --no-install-recommends mssql-tools mssql-server dotnet-runtime-2.2 dotnet-sdk-3.1 libc6-dev libgdiplus
- sudo /opt/mssql/bin/mssql-conf -n setup accept-eula

script:
- dotnet publish "./Tools/rdmp" -r linux-x64
- ./Tools/rdmp/bin/Debug/netcoreapp2.2/linux-x64/rdmp install localhost TEST_ -D -u sa -p YourStrong!Passw0rd
- dotnet test "Reusable/Tests/ReusableCodeTests/ReusableCodeTests.csproj"
- dotnet test "./Rdmp.Core.Tests/Rdmp.Core.Tests.csproj" 
#- dotnet test "./Rdmp.Core.Tests/Rdmp.Core.Tests.csproj" --logger:"console;verbosity=detailed" --filter "FullyQualifiedName~QueryCachingCrossServerTests" --no-build

after_success:
- docker build .
# docker push ...
