version: 1.0.{build}
init:
  - cmd: if defined APPVEYOR_PULL_REQUEST_NUMBER appveyor exit
  - git config --global core.autocrlf true
image: Visual Studio 2019
services:
  - mssql2017
  - mysql
  - postgresql101

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

before_build:
- dotnet restore --packages ./packages
- choco install opencover.portable

build_script:
  - ps: |
      [System.IO.File]::Move("./Tests.Common/TestDatabases.appveyor.txt","./Tests.Common/TestDatabases.txt",$true)
      [System.IO.File]::Move("./Tests.Common/Databases.appveyor.yaml","./Tools/rdmp/Databases.yaml",$true)
      dotnet run --project tools\rdmp\rdmp.csproj install localhost\SQL2017 TEST_ -D -u sa -p Password12!
      dotnet run --project tools\rdmp\rdmp.csproj  cmd CreatePrivateKey ./MyKey.key
  
  # Run code coverage on non UI tests
  - cmd: "OpenCover.Console.exe -returntargetcode -target:\"c:/program files/dotnet/dotnet.exe\" -targetargs:\"test ./scripts/run-all-tests.proj -f net5.0 -c Release -p:BuildInParallel=false\" -filter:\"+[*Rdmp.Core*]* +[*ReusableLibraryCode*]* +[*MapsDirectlyToDatabaseTable*]* -[*Tests*]*\"  -output:coverage.xml -register:path64 -hideskipped:File -skipautoprops"
  - cmd: packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

test: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: CmtrH/h57hWTM17zwN6LUKin9nzebssvZoADRZIIbj2NH//QQVoDEqF6UW8tkg4U
